# Without running the following code, what do you think it will do?

# def foo(first, second=3, third):
#     print(first)
#     print(second)
#     print(third)

# foo(42)

I think this code will raise an error because having a default parameter followed by a non-default parameter isn't allowed.